### ISSUE TITLE
Support for Unicode SSID's

### ISSUE THREAD

**Issue by setBoolean** [fyr77/dns-mobileconfig#11]
Would it be possible to add Unicode support for SSID's e.g. emojis are not probably recognized as exceptions.

**Comment by fyr77** [comment]
I wasn't even aware that SSIDs support unicode haha.
I will look into that.

**Comment by fyr77** [comment]
From quickly testing, I found that dns.notjakob.com itself does put Emojis and Unicode Characters into the generated mobileconfig just fine. The problem here is that Unicode characters are illegal in XML per spec, they need to be encoded in some way.
Furthermore, I do not know how/if iOS and macOS actually decrypt unicode characters in the mobileconfig files. 
Lastly, I do not want to write a translation database for how **all** unicode characters correspond to their "proper" XML format, even if I did understand how iOS/macOS reads these.
I suggest trying [DNSecure](https://github.com/kkk669/DNSecure), maybe that works for your use case.

Sorry for turning this down that quickly. If I do find a way in the future, I will update this issue.

**Comment by setBoolean** [comment]
>From quickly testing, I found that dns.notjakob.com itself does put Emojis and Unicode Characters into the generated mobileconfig just fine.

That is not correct, if for example `🙂` is the input SSID your output in the generated XML is `<string>&</string>`.

> The problem here is that Unicode characters are illegal in XML per spec.

Nope.

> Furthermore, I do not know how/if iOS and macOS actually decrypt unicode characters in the mobileconfig files.

Every Apple OS/Device ist fully unicode compliant for ages now. The same should apply to a tool that is exclusivly for those devices.

> I suggest trying DNSecure, maybe that works for your use case.

Thanks, I will try that one out.

**Comment by fyr77** [comment]
Alright, I might have dismissed this to quickly. I'll test a bit more and see if I can implement this.

**Comment by setBoolean** [comment]
As far as i tested it, the error happens when storing the value in your cookie.

e.g. `😘` translates to a value of `9` in `0exclWifi`

**Comment by fyr77** [comment]
Testing with Chromium and Firefox on Windows results in `😘` being stored in the cookie (and the resulting file).

I have attached a file generated using Chromium. 
[mobileconfig.zip](https://github.com/fyr77/dns-mobileconfig/files/6107773/mobileconfig.zip)

Testing using my iPad results in the SSID-matching being skipped altogether. I assume I have to encode the unicode in some way for it to be stored into the cookie properly by iOS.
The weird thing here is the value of `9` that you got for `😘`. Since there is a value, shouldn't that be read out? That shouls result in the SSID `9` being excluded, which does not happen.

Are you testing this on a mac? I haven't found a way to debug cookies on iOS...

**Comment by setBoolean** [comment]
This is weird, when using Firefox 86.0 (Mac) the Emoji gets probably translated `😘` into the resulting mobileconfig. Using Safari 14.0.3 results in a value of `9`.

**Comment by fyr77** [comment]
Using https://inspect.dev I found out that iOS Safari doesn't even assign some bogus value to emojis, it just drops them altogether. 
The problem here is the cookie. It works fine on https://apple.nextdns.io, so I am going to try to encode unicode into cookies and decode them when generating XML.

**Comment by setBoolean** [comment]
Maybe this will help https://stackoverflow.com/a/4906956.

**Comment by fyr77** [comment]
> 
> 
> Maybe this will help https://stackoverflow.com/a/4906956.

Thanks to this, using unicode now works. I have no clue why I didn't think of that earlier.
Thanks to @setBoolean for being persistent ;)

**Comment by setBoolean** [comment]
Also working on Safari for Mac now 👍. Thank you for fixing this so fast.
